language: python

python: 3.7
dist: xenial
sudo: true 

services:
  - postgresql

env:
  - DJANGO_VERSION=2.0.7

before_script:
  - psql -c 'CREATE DATABASE haven_db;' -U postgres

 
install:
  - pip install -r requirements.txt

run:
  - "python manage.py makemigrations --settings=authors.settings.testing"
  - "python manage.py migrate --settings=authors.settings.testing"


script:
  - coverage run --source='.' manage.py test --settings=authors.settings.testing

after_success:
  - coveralls

  