# Generated by Django 2.0.7 on 2018-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
