# Generated by Django 2.0.7 on 2018-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180809_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likesCount',
            field=models.IntegerField(default=0),
        ),
    ]
