# Generated by Django 2.0.7 on 2018-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180731_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='favoritesCount',
            field=models.IntegerField(default=0),
        ),
    ]
