# Generated by Django 2.0.7 on 2018-08-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikesCount',
            field=models.IntegerField(default=0),
        ),
    ]
