# Generated by Django 2.0.7 on 2018-08-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180806_1154'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='rating',
            managers=[
            ],
        ),
    ]
