# Generated by Django 2.0.7 on 2018-08-06 15:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20180806_1521'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('av_rating', django.db.models.manager.Manager()),
            ],
        ),
    ]
