# Generated by Django 2.0.7 on 2018-08-06 16:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20180806_1603'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('ratings', django.db.models.manager.Manager()),
            ],
        ),
    ]
