# Generated by Django 2.0.7 on 2018-08-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
