# Generated by Django 2.0.7 on 2018-08-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_auto_20180806_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
