# Generated by Django 2.0.7 on 2018-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_article_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
