# Generated by Django 2.0.7 on 2018-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_auto_20180806_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
