# Generated by Django 2.0.7 on 2018-08-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180807_0833'),
        ('articles', '0021_auto_20180806_2213'),
    ]

    operations = [
    ]
