# Generated by Django 2.0.7 on 2018-08-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_auto_20180808_1545'),
        ('articles', '0009_article_dislikescount'),
    ]

    operations = [
    ]
